baseurl = "http://genat.uk/"
relativeurls = true
languageCode = "en-us"
title = "Vladimir Kiselev"
theme = "hugo-lithium-theme"
publishDir = "docs"
googleAnalytics = "UA-57698291-1"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Stuff"
    url = "/stuff/"

[params]
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.9.0"
    highlightjsLang = ["r", "yaml", "tex", "bash"]
    highlightjsTheme = "github"
    Author = "Vladimir Kiselev"
    disqusShortname = "genatuk"
